-- generated by ./tools/gen_needed_translations.sh
-- Updated with additional missing translations
neededTranslations = {
  -- Rule violation types
  '1a) Offensive Name', '1b) Invalid Name Format', '1c) Unsuitable Name',
  '1d) Name Inciting Rule Violation', '2a) Offensive Statement', '2b) Spamming',
  '2c) Illegal Advertising', '2d) Off-Topic Public Statement', '2e) Non-English Public Statement',
  '2f) Inciting Rule Violation', '3a) Bug Abuse', '3b) Game Weakness Abuse',
  '3c) Using Unofficial Software to Play', '3d) Hacking', '3e) Multi-Clienting',
  '3f) Account Trading or Sharing', '4a) Threatening Gamemaster',
  '4b) Pretending to Have Influence on Rule Enforcement', '4c) False Report to Gamemaster',
  
  -- Common UI elements
  'Accept', 'Account name', 'Account Status', 'Action', 'Activate ignorelist', 'Activate whitelist',
  'Add', 'Add new server', 'Add new VIP', 'Addon 1', 'Addon 2', 'Addon 3', 'Add to VIP list',
  'Adjust volume', 'All', 'All modules and scripts were reloaded.', 'Allow auto chase override',
  'Allowed Players', 'Allow VIPs to message you', 'Ambient light: %s%%', 'Amount', 'Anonymous',
  'Any', 'Attack', 'Auction End', 'Audio', 'Authenticator Token', 'Author', 'Autoload',
  'Autoload priority', 'Auto login', 'Auto login selected character on next charlist load',
  
  -- Combat skills
  'Axe Fighting', 'Balance', 'Banishment', 'Banishment + Final Warning', 'Battle', 'Browse',
  'Browse Field', 'Bug report sent.', 'Button Assign', 'Buy', 'Buyer Name', 'Buy Now', 'Buy Offers',
  'Buy with backpack', 'Cancel', 'Cannot login while already in game.', 'Cap', 'Capacity', 'Center',
  'Change language', 'Channel appended to %s', 'Channels', 'Character List', 'Classic control',
  'Clear current message window', 'Clear Messages', 'Clear object', 'Client needs update.',
  'Client Version', 'Close', 'Close this channel', 'Club Fighting', 'Combat Controls', 'Comment',
  
  -- Connection messages
  'Connecting to game server...', 'Connecting to login server...', 'Connection Error',
  'Connection failed.', 'Connection failed, the server address does not exist.',
  'Connection refused, the server might be offline or restarting.\nPlease try again later.',
  'Connection timed out. Either your network is failing or the server is offline.', 'Console',
  
  -- Cooldowns and copying
  'Cooldown', 'Cooldowns', 'Copy', 'Copy message', 'Copy name', 'Copy Name', 'Create Map Mark',
  'Create mark', 'Create New Offer', 'Create Offer', 'Critical Hit Chance', 'Critical Hit Damage',
  'Current hotkeys', 'Current hotkey to add: %s', 'Current Offers', 'Default', 'Delete mark',
  
  -- Description and settings
  'Description', 'Destructive Behaviour', 'Detail', 'Details',
  'Disable chat mode, allow to walk using WASD',
  'Disable Shared Experience', 'Dismount', 'Display connection speed to the server (milliseconds)',
  'Display creature health bars', 'Display creature names', 'Display player mana bar',
  'Display text messages', 'Distance Fighting', '%d of experience per hour',
  "Don't stretch/shrink Game Window", 'Druid', 'Edit hotkey text', 'Edit List', 'Edit %s',
  'Edit Text', 'Edit VIP list entry', 'Enable audio', 'Enable chat mode', 'Enable dash walking',
  'Enable lights', 'Enable music sound', 'Enable Shared Experience', 'Enable smart walking',
  'Enable vertical synchronization', 'Enter Game', 'Enter one name per line.',
  'Enter with your account again to update your client.', 'Error', '(ERROR %d)',
  
  -- Game messages
  'Excessive Unjustified Player Killing', 'Exclude from private chat', 'Exit', 'Experience',
  'Filter list to match your level', 'Filter list to match your vocation', 'Filters', 'Find',
  'Fishing', 'Fist Fighting', 'Follow', 'Force Exit', 'Formula', 'For Your Information',
  'Free Account', 'Fullscreen', 'Game', 'Game framerate limit: %s', 'Global ignore settings',
  'Global whitelist settings', 'Graphics', 'Graphics card driver not detected', 'Group', 'Head',
  'Healing', 'Health Info', 'Health Information', 'Hide monsters', 'Hide non-skull players',
  'Hide Npcs', 'Hide Offline', 'Hide party members', 'Hide players',
  'Hide spells for higher exp. levels', 'Hide spells for other vocations', 'Hit Points',
  
  -- Help text
  'Hold left mouse button to navigate\nScroll mouse middle button to zoom\nRight mouse button to create map marks\nPress Ctrl+Shift+M to view the entire game map',
  'Host', 'Hotkey delay: %dms', 'Hotkey delay: %sms', 'Hotkeys',
  "If you shut down the program, your character might stay in the game.\nClick on 'Logout' to ensure that you character leaves the game properly.\nClick on 'Exit' if you want to exit the program without logging out your character.",
  
  -- Ignore settings
  'Ignore', 'Ignore capacity', 'Ignored Players', 'Ignore equipped', 'Ignore List',
  'Ignore players', 'Ignore Private Messages', 'Ignore Yelling', 'Interface framerate limit: %s',
  'Invalid authentification token.', 'Inventory', 'Invite to Party', 'Invite to private chat',
  'IP Address Banishment', 'Item Name', 'Item Offers', 'It is empty.', "Join %s's Party", 'Knight',
  
  -- Leveling
  'Leave Party', 'Level', 'Life Leech Amount', 'Life Leech Chance', 'Lifetime Premium Account',
  'Limits FPS to 60', "List of items that you're able to buy",
  "List of items that you're able to sell", 'Load', 'Login', 'Login Error',
  'Logout', 'Look', 'Magic Level',
  "Make sure that your client uses\nthe correct game client version", 'Mana', 'Market',
  'Market Error', 'Market Offers', 'Message of the day', 'Message to ', 'Message to %s', 'Minimap',
  
  -- Module management
  'Module Manager', 'Module name', 'Mount', 'Move Stackable Item', 'Move up', 'Music volume: %d',
  'My Offers', 'Name', 'Name Report', 'Name Report + Banishment',
  'Name Report + Banishment + Final Warning', 'New Server', 'Next level in %d hours and %d minutes',
  'No',
  "No graphics card detected, everything will be drawn using the CPU,\nthus the performance will be really bad.\nPlease update your graphics driver to have a better performance.",
  'No item selected.', 'No Mount', 'No Outfit', 'No statement has been selected.', 'Notation',
  'Notify-Login', 'NPC Trade', 'Offer History', 'Offers', 'Offer Type', 'Offline Training', 'Ok',
  'on %s.\n', 'Open', 'Open a private message channel',
  'Open charlist automatically when starting client', 'Open in new window', 'Open new channel',
  'Open purse', 'Open PvP', 'Open PvP Situations', 'Options', 'Overview', 'Paladin',
  
  -- Party and password
  'Pass Leadership to %s', 'Password', 'Piece Price', 'Please enter a character name',
  'Please, press the key you wish to add onto your hotkeys manager', 'Please Select',
  'Please state the rule violation in one clear sentence and wait for a reply from a gamemaster. Please note that your message will disappear if you close the channel.',
  'Please use this dialog to only report bugs. Do not report rule violations here!', 'Please wait',
  'Please wait patiently for a gamemaster to reply', 'Port', 'Position', 'Premium',
  'Premium Account (%s) days left', 'Price', 'Primary', 'Process', 'Protocol', 'Quest Log',
  
  -- Randomize and settings
  'Randomize', 'Randomize characters outfit', 'Reason', 'Refresh', 'Refresh Offers',
  'Regeneration Time', 'Reject', 'Reload All', 'Remember account and password when starts client',
  'Remember password', 'Remove ', 'Remove', 'Remove %s', 'Report Bug', 'Report Rule',
  'Report Rule Violation', 'Reserved for more functionality later.', 'Reset All', 'Reset Market',
  'Reset selection, filters & search', "Revoke %s's Invitation", 'Rotate', 'Rule Violation',
  'Rule Violations', 'Save', 'Save Messages', 'Search', 'Search all items', 'Secondary', 'Select',
  'Select all', 'Select object', 'Select Outfit', 'Select your language', 'Sell', 'Sell All',
  'Seller Name', 'Sell Now', 'Sell Offers', 'Send', 'Send automatically', 'Send Message', 'Server',
  'Server list', 'Server List', 'Server Log', 'Set Outfit', '%s has finished the request',
  '%s has logged in.', '%s has logged out.', 'Shielding', 'Show all items', 'Show connection ping',
  'Show Depot Only', 'Show event messages in console', 'Show frame rate',
  'Show info messages in console', 'Show left panel', 'Show levels in console', 'Show Offline',
  'Show private messages in console', 'Show private messages on screen', 'Show Server Messages',
  'Show status messages in console', 'Show Text', 'Show timestamps in console', 'Show Top Menu',
  'Show your depot items only', 'Skills', 'Skull Time', '%s of experience left', 'Sorcerer',
  'Sort by name', 'Sort by status', 'Sort by type', 'Soul', 'Soul Points', 'Special', 'Speed',
  'Spell Cooldowns', 'Spell List', 'Stamina', 'Statement', 'Statement Report', 'Statistics',
  'Stay logged during session', 'Stop Attack', 'Stop Follow', 'Support', '%s: (use object)',
  '%s: (use object on target)', '%s: (use object on yourself)', '%s: (use object with crosshair)',
  'Sword Fighting', 'Terminal', 'There is no way.',
  'This offer is 25%% above the average market price',
  'This offer is 25%% below the average market price', 'Total Price', 'Trade', 'Trade with ...',
  'Trying to reconnect in %s seconds.', 'Turn delay: %dms', 'Turn delay: %sms',
  'Two-Factor Authentification', 'Type',
  "Unable to load dat file, please place a valid dat in '%s'",
  "Unable to load spr file, please place a valid spr in '%s'", 'Unignore', 'Unjustified Points',
  'Unload', 'Update needed', 'Use', 'Use on target', 'Use on yourself',
  'Use with ...', 'Version', 'VIP List', 'Voc.', 'Vocation', 'Waiting List', 'Website', 'Weight',
  'Will boost your walk on high speed characters',
  'Will detect when to use diagonal step based on the\nkeys you are pressing', 'With crosshair',
  
  -- Status effects
  'Yes', 'You are bleeding', 'You are burning', 'You are cursed', 'You are dazzled',
  'You are dead.', 'You are dead', 'You are drowning', 'You are drunk', 'You are electrified',
  'You are freezing', 'You are hasted', 'You are hungry', 'You are paralysed', 'You are poisoned',
  'You are protected by a magic shield', 'You are strengthened', 'You are within a protection zone',
  'You can enter new text.', 'You have %s percent', 'You have %s percent to go',
  'You may not logout during a fight', 'You may not logout or enter a protection zone',
  'You must enter a comment.', 'You must enter a valid server address and port.',
  'You must select a character to login!', 'You must select an action.',
  'You must select a reason.', 'Your Capacity', 'Your client needs updating, try redownloading it.',
  "Your connection has been lost.\nEither your network or the server went down.",
  'You read the following, written by \n%s\n', 'You read the following, written on \n%s.\n',
  'Your Money', 'Your request has been closed',
  
  -- NEW: Additional translations for missing strings
  'Journey Onwards', 'Email:', 'Acc Name:', 'Remember Email:', 'Remember password:',
  'Add hotkey preset', 'Add new group', 'Copy hotkey preset', 'Rename hotkey preset',
  'Enter a name for the new preset:', 'Enter a name for the preset:',
  'Do you really want to delete the hotkey preset %s?',
  'Current hotkey to change: %s', 'Current hotkey to change: none',
  'Edit Primary Key for \\', 'Edit Secondary Key for \\', 'Edit group %s', 'Remove group %s',
  'Hide groups', 'Show groups', 'Maximum of User-Created Groups Reached',
  
  -- Cyclopedia and trackers
  'Cyclopedia', 'Bestiary Tracker', 'Bosstiary Tracker', 'Imbuement Tracker',
  'Prey Tracker', 'Prey Dialog', 'Select monster', 'Select monster to proceed.',
  
  -- Charms
  'Confirm Charm Removal', 'Confirm Selected Charm', 'Confirm Unlocking of Charm',
  'Do you want to remove the Charm %s from this creature? This will cost you %s gold pieces.',
  'Do you want to use the Charm %s for this creature?',
  
  -- Rarity
  'Common', 'Uncommon', 'Rare', 'Semi-Rare', 'Very Rare',
  
  -- House system
  'Confirm House Action', 'Do you really want to keep your house ',
  'Do you really want to move out of the house ',
  'You have sucessfully accepted the transfer.',
  'You have sucessfully iniated your move out.',
  'You have sucessfully initiated the transfer of your house.',
  
  -- Imbuing
  'Confirm Imbuing Attempt', 'Confirm Clearing', 'Confirmation of Purchase',
  
  -- Chat modes
  'Chat Off', 'Chat On', 'Toggle WASD chat mode', 'Toggle chase mode', 'Local Chat',
  'Close Read-Only Tab', 'Close read-only', 'Open read-only',
  
  -- UI elements
  'Debug Info', 'Top', 'Bottom', 'Parallel', 'Compact', 'Large',
  'Animated Message Scale: %sx', 'Opacity', 'Opacity: %s', 'Opacity Effect: %s%%',
  'Distance', 'Distance: %s',
  
  -- VIP and status
  'Hide', 'Show', 'Show ', 'Hide Customisable Status Bars',
  'Show health', 'Show inventory', 'Show miniMap',
  
  -- Battle
  'Attack next creature in battle list', 'Attack previous creature in battle list', 'Loot corpse',
  
  -- Store
  'Store shop', 'Rewards', 'Open Boss Slots dialog', 'Open Bosstiary dialog',
  'Open QuestLog Tracker', 'Open rewardWall', 'Highscores',
  
  -- Updater
  'Downloading:\n%s', 'Downloading (%i retry):\n%s', 'Updater Error',
  'Updating %i files', 'Updating client (may take few seconds)', 'Timeout',
  
  -- Login
  'Connecting to login server...\nServer: [%s]',
  'ERROR , try adding \n- ip/login.php \n- Enable HTTP login',
  
  -- Loot
  'Invalid Loot Container', 'Manage Loot Containers',
  
  -- Tasks
  'Tasks', 'Do you really want to abort this task?', 'Summary',
  
  -- Account
  'Manage Account', 'Manage control buttons', 'Gratis Premium Account', 'Free',
  
  -- Time
  'You have %s hours and %s minutes left',
  'If you are premium player, you will gain 50%% more experience',
  'Now you will gain 50%% more experience', 'infinite bonus',
  
  -- Coins
  'Transferable Tibia Coins: ', 'Transferable Task points: ',
  
  -- Items
  'Wrap', 'Unwrap',
  
  -- Status effects (new)
  '(Frozen)', ' (Suspended)',
  'You are Agony', 'You are Bleeding', 'You are Feared', 'You are GoshnarTaint',
  'You are GreaterHex', 'You are IntenseHex', 'You are LesserHex',
  'You are NewManaShield', 'You are Rooted', 'You are inspecting',
  
  -- Misc
  'You read the following', 'ok', 'remove',
  '%s of experience per hour', '%s: ',
  ', written by \n%s\n', ', written on \n%s.\n',
  'You have %s percent to go '
}
