//! LR-025: Synchronizacja listy serwerów z manifestu do plików klienta.
//!
//! Launcher aktualizuje plik listy serwerów klienta na podstawie
//! danych z manifestu (servers[]). Gracz nie edytuje listy ręcznie —
//! wybór świata odbywa się w kliencie.

use std::fs;
use std::path::Path;

use common_models::manifest::ServerEntryRaw;

/// Błędy synchronizacji listy serwerów.
#[derive(Debug, thiserror::Error)]
pub enum ServerlistError {
    #[error("I/O error ({context}): {source}")]
    IoError {
        context: String,
        #[source]
        source: std::io::Error,
    },

    #[error("No servers to sync")]
    NoServers,
}

/// Synchronizuje listę serwerów do pliku Lua klienta.
///
/// Generuje plik `init_serverlist.lua` (lub inny konfigurowalny)
/// z tabelą serwerów do użycia przez klienta OTClient.
pub fn sync_serverlist(
    servers: &[ServerEntryRaw],
    output_path: &Path,
) -> Result<(), ServerlistError> {
    if servers.is_empty() {
        tracing::warn!("Brak serwerów do synchronizacji w manifeście");
        return Ok(()); // Nie błąd krytyczny — manifest może nie mieć serwerów
    }

    let lua_content = generate_serverlist_lua(servers);

    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent).map_err(|e| ServerlistError::IoError {
            context: "create serverlist dir".into(),
            source: e,
        })?;
    }

    // Atomowy zapis: tmp → rename
    let tmp_path = output_path.with_extension("lua.tmp");

    fs::write(&tmp_path, lua_content.as_bytes()).map_err(|e| ServerlistError::IoError {
        context: "write serverlist tmp".into(),
        source: e,
    })?;

    fs::rename(&tmp_path, output_path).map_err(|e| ServerlistError::IoError {
        context: "rename serverlist".into(),
        source: e,
    })?;

    tracing::info!(
        "Zsynchronizowano {} serwerów do {}",
        servers.len(),
        output_path.display()
    );

    Ok(())
}

/// Generuje zawartość pliku Lua z listą serwerów.
fn generate_serverlist_lua(servers: &[ServerEntryRaw]) -> String {
    let mut lua = String::new();
    lua.push_str("-- Wygenerowane automatycznie przez launcher. Nie edytuj ręcznie.\n");
    lua.push_str("-- Auto-generated by launcher. Do not edit manually.\n\n");
    lua.push_str("MANAGED_SERVER_LIST = {\n");

    for server in servers {
        if !server.visible || !server.enabled {
            continue;
        }

        lua.push_str("  {\n");
        lua.push_str(&format!("    id = \"{}\",\n", escape_lua(&server.id)));
        lua.push_str(&format!("    name = \"{}\",\n", escape_lua(&server.name)));
        lua.push_str(&format!("    host = \"{}\",\n", escape_lua(&server.host)));
        lua.push_str(&format!("    port = {},\n", server.port));

        if let Some(ref mode) = server.game_mode {
            lua.push_str(&format!("    gameMode = \"{}\",\n", escape_lua(mode)));
        }

        lua.push_str(&format!("    priority = {},\n", server.priority));

        if let Some(ref channel) = server.channel {
            lua.push_str(&format!("    channel = \"{}\",\n", escape_lua(channel)));
        }

        lua.push_str("  },\n");
    }

    lua.push_str("}\n");
    lua
}

/// Escape string for Lua string literal.
fn escape_lua(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\0', "")
}

/// Generuje listę serwerów w formacie JSON (alternatywny format).
pub fn sync_serverlist_json(
    servers: &[ServerEntryRaw],
    output_path: &Path,
) -> Result<(), ServerlistError> {
    if servers.is_empty() {
        return Ok(());
    }

    let json =
        serde_json::to_string_pretty(servers).unwrap_or_else(|_| "[]".to_string());

    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent).map_err(|e| ServerlistError::IoError {
            context: "create serverlist dir".into(),
            source: e,
        })?;
    }

    let tmp_path = output_path.with_extension("json.tmp");
    fs::write(&tmp_path, json.as_bytes()).map_err(|e| ServerlistError::IoError {
        context: "write serverlist json tmp".into(),
        source: e,
    })?;

    fs::rename(&tmp_path, output_path).map_err(|e| ServerlistError::IoError {
        context: "rename serverlist json".into(),
        source: e,
    })?;

    Ok(())
}

// ─────────────────────────────────────────────
// Testy
// ─────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_servers() -> Vec<ServerEntryRaw> {
        vec![
            ServerEntryRaw {
                id: "classic74-main".to_string(),
                name: "Classic 7.4".to_string(),
                host: "classic.example.com".to_string(),
                port: 7171,
                game_mode: Some("classic74".to_string()),
                visible: true,
                enabled: true,
                priority: 10,
                channel: Some("stable".to_string()),
            },
            ServerEntryRaw {
                id: "modern-main".to_string(),
                name: "Modern".to_string(),
                host: "modern.example.com".to_string(),
                port: 7171,
                game_mode: Some("modern".to_string()),
                visible: true,
                enabled: true,
                priority: 20,
                channel: None,
            },
            ServerEntryRaw {
                id: "hidden-test".to_string(),
                name: "Hidden Test".to_string(),
                host: "test.example.com".to_string(),
                port: 7172,
                game_mode: None,
                visible: false,
                enabled: true,
                priority: 100,
                channel: Some("test".to_string()),
            },
        ]
    }

    #[test]
    fn test_generate_lua() {
        let servers = sample_servers();
        let lua = generate_serverlist_lua(&servers);

        assert!(lua.contains("MANAGED_SERVER_LIST"));
        assert!(lua.contains("classic.example.com"));
        assert!(lua.contains("modern.example.com"));
        // Ukryty serwer nie powinien być w wyjściu
        assert!(!lua.contains("test.example.com"));
    }

    #[test]
    fn test_sync_serverlist_to_file() {
        let tmp = tempfile::tempdir().expect("tmpdir");
        let output = tmp.path().join("data/serverlist.lua");

        let servers = sample_servers();
        sync_serverlist(&servers, &output).expect("sync");

        assert!(output.exists());
        let content = std::fs::read_to_string(&output).expect("read");
        assert!(content.contains("Classic 7.4"));
        assert!(content.contains("Modern"));
    }

    #[test]
    fn test_sync_empty_servers() {
        let tmp = tempfile::tempdir().expect("tmpdir");
        let output = tmp.path().join("serverlist.lua");

        let result = sync_serverlist(&[], &output);
        assert!(result.is_ok());
        // Plik nie powinien zostać utworzony (brak serwerów)
        assert!(!output.exists());
    }

    #[test]
    fn test_escape_lua() {
        assert_eq!(escape_lua("normal"), "normal");
        assert_eq!(escape_lua("with\"quotes"), "with\\\"quotes");
        assert_eq!(escape_lua("back\\slash"), "back\\\\slash");
        assert_eq!(escape_lua("new\nline"), "new\\nline");
    }

    #[test]
    fn test_sync_serverlist_json() {
        let tmp = tempfile::tempdir().expect("tmpdir");
        let output = tmp.path().join("servers.json");

        let servers = sample_servers();
        sync_serverlist_json(&servers, &output).expect("sync json");

        assert!(output.exists());
        let content = std::fs::read_to_string(&output).expect("read");
        assert!(content.contains("classic74-main"));
    }
}
