-- ============================================
-- GAME I18N TRANSLATIONS - HE
-- ============================================
-- Auto-generated by json_to_lua_locales.py
-- Total translations: 11
--
--   actions: 0
--   errors: 0
--   events: 0
--   items: 0
--   messages: 11
--   monsters: 0
--   npc: 0
--   quests: 0
--   scripts: 0
--   server: 0
--   spells: 0
--   ui: 0
-- ============================================

local gameTranslations = {
  ["Fg0"] = "Sold {1}x {2} for {3} gold.",
  ["Fg1"] = "Venture the path of decay!",
  ["Fgr"] = "You are already blessed.",
  ["Fgs"] = "You received the remaining {1} blesses.",
  ["Fgt"] = "You gained {1} experience points.",
  ["Fgu"] = "You gained a {1}.",
  ["Fgv"] = "You earned {1} point(s) on the {2} mission.",
  ["Fgw"] = "Congratulations you received the {1} mount.",
  ["Fgx"] = "Your supply stash contains {1} items.",
  ["Fgy"] = "Please make sure you have free slots in your store inbox.",
  ["Fgz"] = "Bought {1}x {2} for {3} gold.",
}

-- Merge with existing locale translations
if locale and locale.translation then
  for key, value in pairs(gameTranslations) do
    locale.translation[key] = value
  end
else
  -- Store for later if locale not yet loaded
  _G.gameTranslations_he = gameTranslations
end