sonar.projectKey=PtakuPL_ooo_canary
sonar.organization=ptakupl
sonar.projectName=ooo-canary
sonar.projectVersion=1.0
sonar.sources=./src
sonar.sourceEncoding=UTF-8
sonar.cfamily.cpp20=true
sonar.exclusions=**/*.html, **/*.css, **/oryginall/**
