-- Migration 011: Add verifier_hash to account_sync_tokens (SEC-P2-001)
-- Tokens are no longer passed via URL query string.
-- A PKCE-like verifier is generated by the issuer, stored as SHA-256 hash,
-- and validated on consumption to prevent token-only replay attacks.

SET @col_exists := (
    SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'account_sync_tokens'
      AND COLUMN_NAME = 'verifier_hash'
);

SET @sql_add := IF(
    @col_exists = 0,
    'ALTER TABLE `account_sync_tokens` ADD COLUMN `verifier_hash` VARCHAR(64) DEFAULT NULL AFTER `metadata_json`',
    'SELECT 1'
);
PREPARE stmt_add FROM @sql_add;
EXECUTE stmt_add;
DEALLOCATE PREPARE stmt_add;

INSERT INTO `_migrations` (`id`, `name`)
VALUES (11, '011_sync_verifier')
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);
