name: Build Canary Engine

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: vcpkg
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Install essential build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake ninja-build g++ git curl zip unzip tar pkg-config

      - name: Install libraries and autotools support
        run: |
          sudo apt-get install -y \
            autoconf automake libtool libtool-bin m4 gperf gettext texinfo \
            libboost-all-dev libbz2-dev libssl-dev libreadline-dev \
            libsqlite3-dev zlib1g-dev tk-dev uuid-dev pkg-config libffi-dev

      - name: Install system python3
        run: sudo apt-get install -y python3 python3-dev python3-pip

      - name: Clean build directory
        run: rm -rf Tibia/silnik/budowa_silnik

      - name: Clone or update vcpkg and install boost only
        run: |
          if [ ! -d "vcpkg" ]; then
            git clone https://github.com/microsoft/vcpkg.git
            ./vcpkg/bootstrap-vcpkg.sh
          else
            cd vcpkg && git pull && ./bootstrap-vcpkg.sh
            cd ..
          fi
          ./vcpkg/vcpkg install boost

      - name: Configure and build
        run: |
          cmake -S Tibia/silnik/canary -B Tibia/silnik/budowa_silnik \
            -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -G Ninja
          cmake --build Tibia/silnik/budowa_silnik --config Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: Tibia/silnik/budowa_silnik
