name: Build Canary Engine

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # CACHE: zmień klucz cache na nowy, aby wymusić świeży cache
      - name: Setup vcpkg cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/vcpkg
            vcpkg/installed
            vcpkg/buildtrees
          key: ${{ runner.os }}-vcpkg-v2-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake ninja-build g++ git curl zip unzip tar pkg-config \
            autoconf automake libtool libtool-bin m4 gperf gettext texinfo \
            libboost-all-dev libbz2-dev libssl-dev libreadline-dev \
            libsqlite3-dev zlib1g-dev tk-dev uuid-dev pkg-config libffi-dev \
            python3 python3-dev python3-pip python3-setuptools \
            libncurses-dev libgdbm-dev libnss3-dev liblzma-dev \
            bison flex gawk

      - name: Clean build directory
        run: rm -rf Tibia/silnik/budowa_silnik

      - name: Setup vcpkg and install dependencies
        run: |
          if [ ! -d "vcpkg" ]; then
            git clone https://github.com/microsoft/vcpkg.git
            ./vcpkg/bootstrap-vcpkg.sh
          fi
          ./vcpkg/vcpkg install boost
          ./vcpkg/vcpkg install python3 --binarysource="clear;default"

      # Jeśli budowa się nie powiedzie, pokaż logi z autoconf
      - name: Show Python3 autoconf log (if build failed)
        if: failure()
        run: |
          cat /home/runner/work/${{ github.repository }}/vcpkg/buildtrees/python3/autoconf-x64-linux-err.log || true

      - name: Configure and build
        run: |
          cmake -S Tibia/silnik/canary -B Tibia/silnik/budowa_silnik \
            -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -G Ninja
          cmake --build Tibia/silnik/budowa_silnik --config Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: Tibia/silnik/budowa_silnik
          
