name: Build Canary

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Restore vcpkg binary cache (including python3)
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/vcpkg/installed
            ${{ github.workspace }}/vcpkg/buildtrees/python3
            ${{ github.workspace }}/vcpkg/packages/python3_*
          key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}-python3

      - name: Install dependencies via vcpkg
        run: |
          ./vcpkg/vcpkg install --triplet x64-linux

      - name: Save vcpkg binary cache (including python3)
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/vcpkg/installed
            ${{ github.workspace }}/vcpkg/buildtrees/python3
            ${{ github.workspace }}/vcpkg/packages/python3_*
          key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}-python3

      - name: Configure project (CMake)
        run: |
          cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build --config Release --parallel
