name: Build Canary Engine

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove vcpkg cache (for debugging)
        run: rm -rf ~/.cache/vcpkg vcpkg/installed vcpkg/buildtrees vcpkg/downloads

      - name: Setup vcpkg cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/vcpkg
            vcpkg/installed
            vcpkg/buildtrees
            vcpkg/downloads
          key: ${{ runner.os }}-vcpkg-v2-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake ninja-build g++ git curl zip unzip tar pkg-config \
            python3.12 python3.12-dev python3-pip python3-setuptools \
            libffi-dev libssl-dev libbz2-dev libreadline-dev libsqlite3-dev zlib1g-dev \
            libncurses-dev libgdbm-dev libnss3-dev liblzma-dev \
            bison flex gawk autoconf automake libtool m4

      - name: Clean build directory
        run: rm -rf Tibia/silnik/budowa_silnik

      - name: Clone vcpkg
        run: |
          if [ ! -d "vcpkg" ]; then
            git clone https://github.com/microsoft/vcpkg.git
          fi

      - name: Bootstrap vcpkg
        run: cd vcpkg && ./bootstrap-vcpkg.sh

      - name: Dump vcpkg dependency tree
        run: ./vcpkg/vcpkg depend-info --dot > deps.dot && cat deps.dot

      - name: Install dependencies via vcpkg
        run: |
          ./vcpkg/vcpkg install boost boost-python

      - name: Show vcpkg build logs if failed
        if: failure()
        run: |
          find vcpkg/buildtrees -name '*-err.log' -exec echo '--- {} ---' \; -exec cat {} \; || true

      - name: Configure and build
        run: |
          cmake -S Tibia/silnik/canary -B Tibia/silnik/budowa_silnik \
            -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -G Ninja
          cmake --build Tibia/silnik/budowa_silnik --config Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: Tibia/silnik/budowa_silnik
